name: VIKTOR CHAGAI BUILDS SO YOU BETTER RUN!!!!!!!!!!!!!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install pdflatex
      run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra make
      
    - name: Build pdf
      run: make ViktorChagai
      
    - name: Upload PDF as artifact (for PR)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ViktorChagai-pdf
        path: ViktorChagai.pdf
        retention-days: 1

    - name: Commit PDF to repo (only on merge to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ViktorChagai.pdf
        if ! git diff --staged --quiet; then
          git commit -m "Auto-build ViktorChagai.pdf [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
